spring.config.import=optional:file:.env[.properties]

server.port=${PORT:8080}
spring.application.name=SoleMate
allowed.origin.url=${SPRING_BASE_URL}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.main.banner-mode=OFF
spring.main.lazy-initialization=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

logging.level.root=INFO