server.port=8080
spring.application.name=SoleMate

spring.datasource.url=jdbc:postgresql://ep-autumn-meadow-a59kt4rh-pooler.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=Bz5TYJlKOwj1&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.main.banner-mode=OFF
spring.main.lazy-initialization=true